# -*- coding: utf-8 -*-
"""early_implementation_pcb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TaYgEjXWvbGX6Kv-4vOvzE7y60c1HO1A
"""

# mounting to gdrive
from google.colab import drive
drive.mount('/content/gdrive')

!pip install -U --pre tensorflow=="2.*"
!pip install tf_slim

!pip install pycocotools

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive/My Drive/project_TA/v1/

!ls

# !git clone https://github.com/tensorflow/models.git
import os
import pathlib


if "models" in pathlib.Path.cwd().parts:
  while "models" in pathlib.Path.cwd().parts:
    os.chdir('..')
elif not pathlib.Path('models').exists():
  !git clone --depth 1 https://github.com/tensorflow/models

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd models/research/
# protoc object_detection/protos/*.proto --python_out=.

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd models/research
# wget https://raw.githubusercontent.com/asyml/texar/master/setup.py

"""**If see error then replace this code to ../models/research/setup.py**


```python
...
    install_requires=[
        'regex',
        'numpy',
        'pathlib',
        'pyyaml',
        'requests',
        'funcsigs',
        'sentencepiece',
        'packaging'
    ],
    extras_require={
        'tensorflow-cpu': [
            'tensorflow>=1.10.0,<2.0',
            'tensorflow-probability>=0.3.0,<0.8.0'
        ],
        'tensorflow-gpu': [
            'tensorflow-gpu>=1.10.0,<2.0',
            'tensorflow-probability>=0.3.0,<0.8.0'
        ]
    },
    package_data={
        "texar": [
            "../bin/utils/multi-bleu.perl",
        ]
    },
    classifiers=[
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Science/Research',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ],
...
```


"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash 
# cd models/research
# pip install .

# Commented out IPython magic to ensure Python compatibility.
# %cd models/research

!touch use_protobuf.py

"""**Copy this code into use_protobuf.py**



```python
import os
import sys
args = sys.argv
directory = args[1]
protoc_path = args[2]
for file in os.listdir(directory):
    if file.endswith(".proto"):
        os.system(protoc_path+" "+directory+"/"+file+" --python_out=.")
```
"""

!python use_protobuf.py object_detection/protos protoc

# Commented out IPython magic to ensure Python compatibility.
# # Install TensorFlow Object Detection API.
# %%bash 
# cp object_detection/packages/tf2/setup.py .
# pip install .

!python object_detection/builders/model_builder_tf2_test.py

!wget https://github.com/matterport/Mask_RCNN/releases/download/v2.1/mask_rcnn_balloon.h5